name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@ec2-3-129-67-242.us-east-2.compute.amazonaws.com << 'EOF'
            # 1. Navegar a la carpeta del proyecto
            cd /home/ec2-user/API_RESTful_Parcial_2

            # 2. Detener el proceso anterior en PM2
            pm2 stop 0

            # 3. Hacer git pull para obtener los últimos cambios
            git pull origin main  # Asegúrate de usar la rama correcta

            # 4. Instalar las dependencias
            sudo npm install

            # 5. Iniciar el proceso nuevamente con PM2
            pm2 start 0
          EOF
